-- mysql -u root -p -- 

/* Modelagem Básica */
NOME - CARACTER(30)
CPF - NUMERICO(11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDERECO - CARACTER(100)
SEXO - CARACTER(1)

/* Processos de Modelagem */
Fase 01 e 02 - AD ADM de Dados
- Modelagem Conceitual: rascunho
- Modelagem Lógica: UML
Fase 03 - DBA ou AD
- Modelagem Física: Scripts de Banco

/* Área de BD ->
OLTP ----------------------------------- OLAP
AD, DBA, Tunning(Analista de Perfomance), BI(passado), DTS(futuro) */



/* VERIFICANDO TABELAS */
SHOW TABLES;

CREATE DATABASE PROJETO;

USE PROJETO;

CREATE TABLE CLIENTE (
	IdCliente int primary key AUTO_INCREMENT,
	Nome varchar(30) not null,
	Sexo enum('M', 'F') not null,
	EMAIL varchar(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE
);


/* DESCOBRINDO A ESTRUTURA DE UMA TABELA */
DESC CLIENTE;


CREATE TABLE ENDERECO (
IDENDERECO int(11) not null PRIMARY KEY AUTO_INCREMENT,
RUA VARCHAR(30) not null,
BAIRRO VARCHAR(30) NOT NULL,
CIDADE VARCHAR(30) NOT NULL,
ESTADO CHAR(2) NOT NULL,
ID_CLIENTE INT UNIQUE,
FOREIGN KEY (ID_CLIENTE)
REFERENCES CLIENTE(ID_CLIENTE)
);


/* INSERT */
INSERT INTO CLIENTE VALUES(NULL, 'PAULA', 'M', NULL, '777');
INSERT INTO ENDERECO VALUES(
	NULL, 'RUA JOAQUIM SILVA', 'ALVORADA', 'NITEROI', 'RJ', 7);

/* alterar valor - update (não esquecer do where) */
SELECT TITULO, PRECO * 1.1 as NOVO_PRECO
FROM LIVRO

"saber modelo de entidade, normalização, fazer um select rápido"
-----------------------------------------------------------------
Curso-banco-dados-01
Banco de Dados = Teoria dos Conjuntos
CREATE TABELA CLIENTE(
IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(30) NOT NULL,
SEXO ENUM('M', 'F') NOT NULL
);


/* Seleções e Projeções*/
SELECT * FROM CLIENTE;

/* FILTRANDO DADOS COM WHERE E LIKE */
SELECT NOME, TELEFONE FROM CLIENTE;

/* FILTRANDO */
SELECT NOME, SEXO FROM CLIENTE 
WHERE SEXO = 'M';

/* Utilizando o LIKE: pesquisar */
SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'RJ';

/* CARACTER CORINGA  % -> Qualquer Coisa*/
SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ'; -- Começa com % e termina com RJ --

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'OSCAR CURY%';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE '%CENTRO%';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE '%_____CENTRO%';


---------------------------------------------------------------------------
Entendendo a Foreign Key
/* Chave Estrangeira é a chave primária de uma tabela que vai a outra
 fazer referência entre registros */
-- Os relacionamentos vão depender do tipo de negócio, nas regras de negócio --
/* Em regra, relacionamento de 1 para 1, a chave estrangeira fica 
na tabela mais fraca */
-- Em relacionamento de 1 para n, a chave estrangeira fica no lado n --
-- todo campo vetorizado vira outra tabela -- 

CONSTRAINT fk_id_Autor FOREIGN KEY (ID_AUTOR)
REFENCES tbl_autores(ID_AUTOR)
---------------------------------------------------------------------
-- SUBSELECT --
SELECT * FROM tbl_livro;

UPDATE tbl_livro
SET precoLivro = PrecoLivro + 1.5
WHERE idEditora = 
	(SELECT idEditora
	FROM tbl_editora
	WHERE NomeEditora = 'Microsoft Press');


--------------- INSERTS ------------------
/*
show databases;
use -database-;
show tables;
DESC tabela;

 */

 CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);

INSERT INTO CLIENTE VALUES('JOAO','M','JOAO@GMAIL.COM',988638273,'22923110','MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('CELIA','F','CELIA@GMAIL.COM',541521456,'25078869','RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTE VALUES('JORGE','M',NULL,885755896,'58748895','OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');

/* FORMA 02 - COLOCANDO AS COLUNAS */

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('LILIAN','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','947785696',887774856);

/* FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL */

INSERT INTO CLIENTE VALUES('ANA','F','ANA@GLOBO.COM',85548962,'548556985','PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP'),
                          ('CARLA','F','CARLA@TERATI.COM.BR',7745828,'66587458','SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');
						  
INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('CLARA','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','883665843',99999999999);

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('CLARA','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','883665843',22222222222);
-----------------------------------------------------------------
DESC ENDERECO;
INSERT INTO ENDERECO 
VALUES(NULL, 'RUA ANTONIO SA', "CENTRO", 'B. HORIZONTE', "MG", 4);

INSERT INTO ENDERECO 
VALUES(NULL, 'RUA CAPITAO HERMES', "CENTRO", 'RIO DE JANEIRO', "RJ", 1);

INSERT INTO ENDERECO 
VALUES(NULL, 'RUA PRESIDENTE VARGAS', "JARDINS", 'SAO PAULO', "SP", 3);

INSERT INTO ENDERECO 
VALUES(NULL, 'RUA ALFANDEGA', "ESTACIO", 'B. HORIZONTE', "RJ", 2);

INSERT INTO ENDERECO 
VALUES(NULL, 'RUA DO OUVIDOR', "CENTRO", 'B. HORIZONTE', "MG", 5);

INSERT INTO ENDERECO 
VALUES(NULL, 'RUA URUGUAIANA', "CENTRO", 'B. HORIZONTE', "MG", 5);

----------------------------------------------------------------
-- Seleção, projeção e junção --
/* SELEÇÃO 
- é projeção
*/
-- todo banco tem seu dicionario de dados --

SELECT now() as DATA_HORA, 'VITOR IPIRANGA' as 'PROGRAMMER';
SELECT NOME as CLIENTE, SEXO, EMAIL, NOW() AS DATA_HORA
FROM CLIENTE;

SELECT ENDERECO, COUNT(*) FROM CLIENTE
GROUP BY ENDERECO;
---------------------------------------------------------------
/* PRIMEIRA FORMA NORMAL 
1 - TODO CAMPO VETORIZADO SE TORNARA OUTRA TABELA
com elementos da mesma familia

[AMARELO, AZUL, LARANJA, VERDE] -> CORES
[FIESTA, UNO, CIVIC, FERRARI] -> CARROS

2 - TODO CAMPO multivalorizado SE TORNARA OUTRA TABELA
quando for divisivel

1 - TODA TABELA PRECISA DE PELO MENOS UM CAMPO QUE 
IDENTIFIQUE O REGISSTRO CCOMO UNICO

*/

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT, 
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,

	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT, 
	TIPO ENUM('RES','COM','CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,

	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);